// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqcbr1_Pw2U2mhq1OPDDgDsHQ2flYBsqw',
    appId: '1:289742049866:web:193794d98b844f2a27ccb3',
    messagingSenderId: '289742049866',
    projectId: 'touristmedicalapp',
    authDomain: 'touristmedicalapp.firebaseapp.com',
    storageBucket: 'touristmedicalapp.appspot.com',
    measurementId: 'G-Z70J6NHXS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrpck45gu0YXMlRnJx9Aa-iDvXLoIx0oQ',
    appId: '1:289742049866:android:f750c266008ccc7927ccb3',
    messagingSenderId: '289742049866',
    projectId: 'touristmedicalapp',
    storageBucket: 'touristmedicalapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvDPaRCWzwLD2aOg4SyPJDGB5HgNIKZ4s',
    appId: '1:289742049866:ios:7bca4ab335f750af27ccb3',
    messagingSenderId: '289742049866',
    projectId: 'touristmedicalapp',
    storageBucket: 'touristmedicalapp.appspot.com',
    iosBundleId: 'com.example.touristMedicalHelpMobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvDPaRCWzwLD2aOg4SyPJDGB5HgNIKZ4s',
    appId: '1:289742049866:ios:a24907b4dcce1c3227ccb3',
    messagingSenderId: '289742049866',
    projectId: 'touristmedicalapp',
    storageBucket: 'touristmedicalapp.appspot.com',
    iosBundleId: 'com.example.touristMedicalHelpMobileapp.RunnerTests',
  );
}
